# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3bff52e77b6bf1a8df3c28605add85da3eedb5489a22769fd45c58ba57db5204b8ed8e6ba4a99abe37d934dd68a833e0a9d0f8a33265a89fe20891df03f0398

test:
  secret_key_base: 992483f5f044aaa8882b7defd873e18b525cacbe4b1fa69a9aff484829560e7f62ebc0c1f872749a95e624652cfd211e6fd4acae835e09b64d0cdd17257c46da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
