# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52cfda3f1c9921edff9ff677c1b56d9816dcbb49766733957441d7e67007e13b6e941b3b11725bf0702ed5a06bb0f7c2492ae0219cb0901324ae9abc2687433f

test:
  secret_key_base: 67ced0a6d93b9e25aa107673e2ae99441b08e203e13f289056241334ff0bb7dc4ba19eb709a4a7319fff706e95b0a4eed38d48c96e8386ec028a4f87dc861382

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
